"""add attendance_date column in tpc_attendance_records table

Revision ID: 1dc7ca7a8dcf
Revises: 
Create Date: 2026-02-20 16:44:45.578503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc7ca7a8dcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ Add column as nullable first
    op.add_column(
        'tpc_attendance_records',
        sa.Column('attendance_date', sa.Date(), nullable=True)
    )

    # 2️⃣ Backfill from existing check_in_time
    op.execute("""
        UPDATE tpc_attendance_records
        SET attendance_date = DATE(check_in_time)
    """)

    # 3️⃣ Make column NOT NULL
    op.alter_column(
        'tpc_attendance_records',
        'attendance_date',
        nullable=False
    )

    # 4️⃣ Add unique constraint
    op.create_unique_constraint(
        'uix_employee_date',
        'tpc_attendance_records',
        ['employee_id', 'attendance_date']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tpc_attendance_records',
        'attendance_date',
        existing_type=sa.Date(),
        nullable=False
    )
    # ### end Alembic commands ###
