"""add must_change_password column in users table

Revision ID: 2fff12890898
Revises: 3a67058d3e27
Create Date: 2026-02-27 12:57:37.162152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2fff12890898"
down_revision: Union[str, Sequence[str], None] = "3a67058d3e27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tpc_users",
        sa.Column(
            "must_change_password",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tpc_users", "must_change_password")
    # ### end Alembic commands ###
