"""convert role to enum

Revision ID: 3a67058d3e27
Revises: 3ae3157eeebb
Create Date: 2026-02-26 15:20:59.520262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3a67058d3e27"
down_revision: Union[str, Sequence[str], None] = "3ae3157eeebb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tpc_employees",
        "email",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "tpc_users",
        "email",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "tpc_users",
        "hashed_password",
        existing_type=mysql.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "tpc_users",
        "role",
        existing_type=mysql.VARCHAR(length=12),
        type_=sa.Enum(
            "SUPERADMIN", "ADMIN", "DRIVER", "HELPER", "EMPLOYEE", name="user_role_enum"
        ),
        nullable=False,
    )
    op.alter_column(
        "tpc_users",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.drop_constraint(
        op.f("fk_tpc_users_employee_id"), "tpc_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "tpc_users", "tpc_employees", ["employee_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tpc_users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_tpc_users_employee_id"),
        "tpc_users",
        "tpc_employees",
        ["employee_id"],
        ["id"],
    )
    op.alter_column(
        "tpc_users",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "tpc_users",
        "role",
        existing_type=sa.Enum(
            "SUPERADMIN", "ADMIN", "DRIVER", "HELPER", "EMPLOYEE", name="user_role_enum"
        ),
        type_=mysql.VARCHAR(length=12),
        nullable=True,
    )
    op.alter_column(
        "tpc_users",
        "hashed_password",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "tpc_users",
        "email",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "tpc_employees",
        "email",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
