"""added employee_id in user

Revision ID: 3ae3157eeebb
Revises: da13764a5f49
Create Date: 2026-02-26 14:43:25.433496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3ae3157eeebb"
down_revision: Union[str, Sequence[str], None] = "da13764a5f49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tpc_users", sa.Column("employee_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(
        "uq_tpc_users_employee_id", "tpc_users", ["employee_id"]
    )
    op.create_foreign_key(
        "fk_tpc_users_employee_id",
        "tpc_users",
        "tpc_employees",
        ["employee_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tpc_users_employee_id", "tpc_users", type_="foreignkey")
    op.drop_constraint("uq_tpc_users_employee_id", "tpc_users", type_="unique")
    op.drop_column("tpc_users", "employee_id")
    # ### end Alembic commands ###
