"""added applicant question and response table

Revision ID: 59ef27f3f90c
Revises: 4db3d4187a58
Create Date: 2026-04-06 17:01:46.813188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "59ef27f3f90c"
down_revision: Union[str, Sequence[str], None] = "4db3d4187a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tpc_applicant_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_key", sa.String(length=100), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=50), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_key"),
    )
    op.create_index(
        op.f("ix_tpc_applicant_questions_question_key"),
        "tpc_applicant_questions",
        ["question_key"],
        unique=False,
    )
    op.create_table(
        "tpc_applicant_qresponses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("applicant_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["applicant_id"], ["tpc_applicants.id"]),
        sa.ForeignKeyConstraint(["question_id"], ["tpc_applicant_questions.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "applicant_id", "question_id", name="uq_applicant_question_response"
        ),
    )
    op.create_index(
        op.f("ix_tpc_applicant_qresponses_applicant_id"),
        "tpc_applicant_qresponses",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tpc_applicant_qresponses_question_id"),
        "tpc_applicant_qresponses",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tpc_applicant_qresponses_question_id"),
        table_name="tpc_applicant_qresponses",
    )
    op.drop_index(
        op.f("ix_tpc_applicant_qresponses_applicant_id"),
        table_name="tpc_applicant_qresponses",
    )
    op.drop_table("tpc_applicant_qresponses")
    op.drop_index(
        op.f("ix_tpc_applicant_questions_question_key"),
        table_name="tpc_applicant_questions",
    )
    op.drop_table("tpc_applicant_questions")
    # ### end Alembic commands ###
