"""create tpc_files table

Revision ID: 7686a2f4dd76
Revises: 93dfa1cb4f66
Create Date: 2026-03-05 14:42:51.463544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7686a2f4dd76"
down_revision: Union[str, Sequence[str], None] = "93dfa1cb4f66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tpc_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["tpc_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_entity_lookup", "tpc_files", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_tpc_files_id"), "tpc_files", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tpc_files_id"), table_name="tpc_files")
    op.drop_index("idx_entity_lookup", table_name="tpc_files")
    op.drop_table("tpc_files")
    # ### end Alembic commands ###
