"""add reminders table

Revision ID: c3033b5f34ea
Revises: 1dc7ca7a8dcf
Create Date: 2026-02-21 16:36:11.496537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3033b5f34ea'
down_revision: Union[str, Sequence[str], None] = '1dc7ca7a8dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tpc_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['tpc_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpc_reminders_id'), 'tpc_reminders', ['id'], unique=False)
    op.alter_column('tpc_attendance_records', 'attendance_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tpc_attendance_records', 'attendance_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_tpc_reminders_id'), table_name='tpc_reminders')
    op.drop_table('tpc_reminders')
    # ### end Alembic commands ###
