"""initial schema

Revision ID: da13764a5f49
Revises:
Create Date: 2026-02-23 09:13:11.013077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "da13764a5f49"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tpc_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tpc_users_email"), "tpc_users", ["email"], unique=True)
    op.create_index(op.f("ix_tpc_users_id"), "tpc_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_tpc_users_username"), "tpc_users", ["username"], unique=True
    )
    op.create_table(
        "tpc_employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("date_hired", sa.Date(), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["tpc_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tpc_employees_email"), "tpc_employees", ["email"], unique=True
    )
    op.create_index(op.f("ix_tpc_employees_id"), "tpc_employees", ["id"], unique=False)
    op.create_table(
        "tpc_reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["tpc_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tpc_reminders_id"), "tpc_reminders", ["id"], unique=False)
    op.create_table(
        "tpc_attendance_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column("check_in_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["tpc_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["tpc_employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tpc_attendance_records_id"),
        "tpc_attendance_records",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tpc_attendance_records_id"), table_name="tpc_attendance_records"
    )
    op.drop_table("tpc_attendance_records")
    op.drop_index(op.f("ix_tpc_reminders_id"), table_name="tpc_reminders")
    op.drop_table("tpc_reminders")
    op.drop_index(op.f("ix_tpc_employees_id"), table_name="tpc_employees")
    op.drop_index(op.f("ix_tpc_employees_email"), table_name="tpc_employees")
    op.drop_table("tpc_employees")
    op.drop_index(op.f("ix_tpc_users_username"), table_name="tpc_users")
    op.drop_index(op.f("ix_tpc_users_id"), table_name="tpc_users")
    op.drop_index(op.f("ix_tpc_users_email"), table_name="tpc_users")
    op.drop_table("tpc_users")
    # ### end Alembic commands ###
