"""models for trip management

Revision ID: fe671760b626
Revises: 2fff12890898
Create Date: 2026-02-28 11:01:42.191085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fe671760b626"
down_revision: Union[str, Sequence[str], None] = "2fff12890898"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tpc_stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "allowed_radius_meters", sa.Integer(), nullable=False, server_default="100"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tpc_stores_id"), "tpc_stores", ["id"], unique=False)
    op.create_table(
        "tpc_trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_no", sa.String(length=100), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ASSIGNED",
                "ACTIVE",
                "PENDING_APPROVAL",
                "COMPLETED",
                "CANCELLED",
                name="trip_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["driver_id"], ["tpc_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_no"),
    )
    op.create_index(op.f("ix_tpc_trips_id"), "tpc_trips", ["id"], unique=False)
    op.create_table(
        "tpc_trip_stops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("stop_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CHECKED_IN",
                "CHECKED_OUT",
                "SKIPPED",
                name="stop_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("check_in_time", sa.DateTime(), nullable=True),
        sa.Column("lat_in", sa.Float(), nullable=True),
        sa.Column("long_in", sa.Float(), nullable=True),
        sa.Column(
            "gps_valid_in", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column("check_out_time", sa.DateTime(), nullable=True),
        sa.Column("lat_out", sa.Float(), nullable=True),
        sa.Column("long_out", sa.Float(), nullable=True),
        sa.Column(
            "gps_valid_out", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column(
            "requires_review", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["tpc_stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["tpc_trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tpc_trip_stops_id"), "tpc_trip_stops", ["id"], unique=False
    )
    op.create_table(
        "tpc_gps_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_stop_id", sa.Integer(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum("CHECK_IN", "CHECK_OUT", name="gps_action_enum"),
            nullable=False,
        ),
        sa.Column("actual_lat", sa.Float(), nullable=False),
        sa.Column("actual_long", sa.Float(), nullable=False),
        sa.Column("store_lat", sa.Float(), nullable=False),
        sa.Column("store_long", sa.Float(), nullable=False),
        sa.Column("calculated_distance", sa.Float(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_stop_id"], ["tpc_trip_stops.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tpc_gps_logs_id"), "tpc_gps_logs", ["id"], unique=False)
    op.create_table(
        "tpc_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=True),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("trip_stop_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("reviewed_by_admin_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["tpc_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_admin_id"],
            ["tpc_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["tpc_trips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_stop_id"],
            ["tpc_trip_stops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tpc_notifications_id"), "tpc_notifications", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tpc_notifications_id"), table_name="tpc_notifications")
    op.drop_table("tpc_notifications")
    op.drop_index(op.f("ix_tpc_gps_logs_id"), table_name="tpc_gps_logs")
    op.drop_table("tpc_gps_logs")
    op.drop_index(op.f("ix_tpc_trip_stops_id"), table_name="tpc_trip_stops")
    op.drop_table("tpc_trip_stops")
    op.drop_index(op.f("ix_tpc_trips_id"), table_name="tpc_trips")
    op.drop_table("tpc_trips")
    op.drop_index(op.f("ix_tpc_stores_id"), table_name="tpc_stores")
    op.drop_table("tpc_stores")
    # ### end Alembic commands ###
